### ISSUE TITLE
zlib1.dll was not found in latest version

### ISSUE THREAD

**Issue by function-store** [EnviralDesign/TD_Launcher#3]
Hi Lucas, in the latest version I'm getting "The code execution cannot process because zlib1.dll was not found.". Also happened on my friend's machine (both Windows 11). Thanks for this piece of software btw, not sure what I'd do without it!

**Comment by eraxeg** [comment]
Same here, on Windows 10

**Comment by monomango-wieland-hilker** [comment]
+1 one me here on win10 as non administrative user.

**Comment by EnviralDesign** [comment]
Thanks for the flag, I will get this fixed soon and have an update in the day or so!

**Comment by EnviralDesign** [comment]
@monomango-wieland-hilker @eraxeg @function-store Sorry for the delay on this, I realize some of you posted a while back about this.

If anyone could try the 1.0.5 release and see if that fixed it or if there are any other dll's still missing please let me know!

https://github.com/EnviralDesign/TD-Launcher/releases/tag/v1.0.5

**Comment by function-store** [comment]
works on my win11, thanks Lucas!

**Comment by EnviralDesign** [comment]
excellent! thanks for checking
